[package]
license = ["Apache-2.0"]
keywords = ["Xero", "Accounts", "Transactions"]
org = "ballerinax"
name = "xero.accounts"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "0.1.0-SNAPSHOT"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
