[package]
license = ["Apache-2.0"]
keywords = ["Marketing/Marketing Automation", "Cost/Paid"]
org = "ballerinax"
name = "constantcontact"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "1.0.1"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
