[package]
license = ["Apache-2.0"]
keywords = ["Marketing/Social Media Accounts", "Cost/Freemium"]
org = "ballerinax"
name = "dev.to"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "1.0.1"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
