[package]
license = ["Apache-2.0"]
keywords = ["Website & App Building/Web Scraper", "Cost/Freemium"]
org = "ballerinax"
name = "webscraping.ai"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "1.0.1"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
