[package]
license = ["Apache-2.0"]
keywords = ["IT Operations/Enterprise Architecture Tools", "Cost/Paid"]
org = "ballerinax"
name = "leanix.integrationapi"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "1.0.1"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
