[package]
license = ["Apache-2.0"]
keywords = ["Business Intelligence/Analytics", "Cost/Paid"]
org = "ballerinax"
name = "aws.athena"
icon = "icon.png"
distribution = "2201.0.0"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "1.0.0"
authors = ["Ballerina"]

[build-options]
observabilityIncluded = true
